gantt
    title Cyanophycin Research Timeline: October - December 2024
    dateFormat MM-DD

    section Milestones
        First Arginine-Auxotroph Titration Study & ALE Run 1 Completed  :done, milestone, ale1, 2024-10-01, 1d
        Arginine-Auxotroph Strains for ALE Created & Validation         :active, milestone, augAuxStrains, 2024-10-08, 1d
        Arginine-Auxotroph ALE with ∆argBR ∆astAC ΩKan +/-∆cphAI        :milestone, ALE, 2024-12-01, 1d

    section Completed Experiments
        EXP008 Arg-Aux Titration Response (high [Arg])              :done, exp008, 2024-10-08, 1w
        EXP009 Arg-Aux Background Growth (0•Arg)                    :done, exp009, 2024-10-15, 1w
        EXP010 Arg-Aux Background Growth (0•Arg                     :done, exp010, 2024-10-22, 1w
        EXP011 Arg-Aux Titration Response                           :done, exp011, 2024-10-29, 1w
        EXP012 Overlap PCR Primer Design and Order                  :done, design, 2024-11-04, 1w
        EXP012 Overlap PCR Construction ∆argR_∆astAC_ΩKan           :active, exp012, 2024-11-11, 1w
        EXP012 Overlap PCR Construct Sequencing                     :exp012, 2024-11-18, 3d
        EXP012 Overlap PCR ADP1 ∆argB +/-∆cphAI transformation      :exp012, 2024-11-21, 3d

    section Upcoming Experiments
        EXP013 ALE Run 2 Exp013                                           :exp013, 2024-11-25, 1w
        EXP014 (Contingency) Experiments Background Growth Resolution     :exp014, after exp013, 1w
        EXP015 (Debugging) Runs Arginine-Auxotrophy ALE                   :exp015, after exp014, 1w

    section Presentations and Deliverables
        MBP Symposium                                              :done, symp, 2024-10-07, 1d
        MBP Progress Report I                                      :active, report1, 2024-11-14, 1d
        MBP Progress Report II                                     :2024-12-13, 1d

    section Holidays and Breaks
        Thanksgiving Break                                         :crit, 2024-11-28, 4d