gantt
    title Research Timeline: October - December 2024
    dateFormat YYYY-MM-DD
    section Milestones
        First Arginine-Auxotroph Titration Study & ALE Run 1 Completed  :done, milestone1, 2024-10-01, 1d
        MBP Symposium                                                :done, milestone2, 2024-10-07, 1d
        Completion of Arginine-Auxotroph Strain Design & Validation  :active, milestone3, 2024-10-08, 2024-11-25
        Next ALE Run 2 Begins                                       :milestone4, 2024-11-26, 1d
    section Experiments
        008 Arginine-Auxotroph Titration Response                   :done, exp1, 2024-10-08, 1w
        009 Arginine-Auxotroph Background                           :done, exp2, 2024-10-15, 1w
        010 Arginine-Auxotroph Background                           :done, exp3, 2024-10-22, 1w
        011 Arginine-Auxotroph Titration Response                   :done, exp4, 2024-10-29, 1w
        012 Overlap PCR & Strain Transformation                     :active, exp5, 2024-11-01, 3w
    section Upcoming Experiments
        ALE Run 2 Exp013                                           :crit, exp6, 2024-11-26, 2w
        Contingency Experiments Background Growth Resolution       :crit, exp7, 2024-12-10, 1w
        Debugging Runs Arginine-Auxotrophy ALE                     :crit, exp8, 2024-12-17, 2w
    section Notes
        90% Complete for Arginine-Auxotroph Strain Design         :crit, note1, 2024-11-20, 1w